name: Terraform Docs

on:
  workflow_call:

jobs:
  terraform_docs:
    name: Terraform Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Terraform Docs v0.16.0
        run: |
          curl -L https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz -o terraform-docs.tar.gz
          tar --extract --file=terraform-docs.tar.gz terraform-docs
          chmod +x terraform-docs
      - name: Run terraform-docs and update the README
        run: |
          git config --global push.default simple
          ./terraform-docs markdown table --hide header . > .README_OUT
          sed -i -ne '/<!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->/{p;r .README_OUT' -e ':a;n;/<!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->/!ba};p' README.md
          rm .README_OUT terraform-docs terraform-docs.tar.gz
          git add README.md
      - name: Commit and push changes
        uses: actions-x/commit@v2
